# -*- coding: utf-8 -*-
"""auto-generate vote

Revision ID: 82c7a20a6956
Revises: a9333f8e681c
Create Date: 2021-11-24 23:11:45.949116

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "82c7a20a6956"
down_revision = "a9333f8e681c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    # ### end Alembic commands ###
