# -*- coding: utf-8 -*-
"""auto generate phone number

Revision ID: a25270136fd4
Revises: 82c7a20a6956
Create Date: 2021-11-24 23:14:22.600815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a25270136fd4"
down_revision = "82c7a20a6956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
